import { REGIONS, type RegionId } from './focus-regions';

// Visual slot registry (CATALOG-ADMIN.md §6, CAT-014). The renderers stay code;
// this makes their coupling to catalog choices explicit. Each slot is one
// drawing property of today's renderers. `keys` are the selection keys
// (attribute codes) that sketch-spec.ts, tailored-human.tsx, garments/*.ts and
// focus-regions.ts read for it; `tokens` are exactly the values those keys can
// hold (the supplied seed, the imported legacy shirt and fit choices) plus the
// literals the code compares against. `shownIn3D` follows garments/coverage.ts.
//
// Slots and tokens are derived from the code, not invented, and are checked
// against the renderer source by tests/visual-registry.test.ts. This module
// changes no rendering: the renderers are rebound to it in WP-14.

export type VisualModel = 'suit' | 'shirt' | 'blazer';
export type VisualSlot = {
  label: string;
  keys: readonly string[];
  tokens: readonly string[];
  shownIn3D: boolean;
  visualModels: readonly VisualModel[];
};

const THREAD_COLOURS = [
  '41',
  '53',
  '42',
  '43',
  '44',
  '54',
  '49',
  '51',
  '52',
  '45',
  '46',
  '47',
  '48',
  '50',
  '40',
] as const;
const OPTIONAL = ['without', 'personalizado'] as const;
const suit: readonly VisualModel[] = ['suit'];
const jacket: readonly VisualModel[] = ['suit', 'blazer'];

export const VISUAL_SLOTS = {
  fit: {
    label: 'Fit',
    keys: ['style.jacket.jacket_fit.jacket-fit', 'style.shirt.shirt_fit.shirt-fit'],
    tokens: ['1', '0', 'relaxed', 'tailored', 'classic'],
    shownIn3D: true,
    visualModels: ['suit', 'shirt', 'blazer'],
  },
  'jacket.style': {
    label: 'Jacket style',
    keys: ['style.jacket.jacket_style_combined.jacket-style-combined'],
    tokens: ['simple_1', 'simple_2', 'simple_3', 'crossed_2', 'crossed_4', 'crossed_6', 'mao'],
    shownIn3D: true,
    visualModels: jacket,
  },
  'jacket.lapelType': {
    label: 'Lapel style',
    keys: ['style.jacket.jacket_lapel_type_combinated.jacket-lapel-type'],
    tokens: ['standard', 'peak', 'round'],
    shownIn3D: true,
    visualModels: jacket,
  },
  'jacket.lapelWidth': {
    label: 'Lapel width',
    keys: ['style.jacket.jacket_lapel_type_combinated.jacket-wide-lapel'],
    tokens: ['narrow', 'standard', 'width'],
    shownIn3D: true,
    visualModels: suit,
  },
  'jacket.pockets': {
    label: 'Pockets',
    keys: ['style.jacket.jacket_pockets_type.jacket-pockets-type'],
    tokens: ['0', '2', '2a', '2b', '3', '3a', '2c', '3c', '2d', '3d'],
    shownIn3D: true,
    visualModels: jacket,
  },
  'jacket.sleeveButtons': {
    label: 'Sleeve buttons',
    keys: ['style.jacket.jacket_sleeve_buttons_combinated.jacket-sleeve-buttons'],
    tokens: ['0', '2', '3', '4'],
    shownIn3D: true,
    visualModels: suit,
  },
  'jacket.sleeveHoles': {
    label: 'Working buttonholes',
    keys: ['style.jacket.jacket_sleeve_buttons_combinated.jacket-sleeve-buttonholes'],
    tokens: ['1', '0'],
    shownIn3D: true,
    visualModels: suit,
  },
  'jacket.vent': {
    label: 'Back vent',
    keys: ['style.jacket.jacket_vent.jacket-vent'],
    tokens: ['0', '1', '2'],
    shownIn3D: true,
    visualModels: suit,
  },
  'jacket.chestPocket': {
    label: 'Breast pocket',
    keys: ['style.jacket.jacket_chest_pocket.jacket-chest-pocket'],
    tokens: ['0', '1', 'patched_1', 'patched_2'],
    shownIn3D: true,
    visualModels: suit,
  },
  'jacket.buttons': {
    label: 'Custom buttons',
    keys: ['accents.jacket.buttons_color.buttons'],
    tokens: ['By default', 'personalizado'],
    shownIn3D: true,
    visualModels: suit,
  },
  'jacket.buttonColor': {
    label: 'Button colour',
    keys: ['accents.jacket.buttons_color.colors'],
    tokens: ['1', '2', '3', '4', '5', '6', '50', '51', '52', '53'],
    shownIn3D: true,
    visualModels: suit,
  },
  'jacket.threads.scope': {
    label: 'Contrast threads',
    keys: ['accents.jacket.button_holes_threads.button-threads-holes'],
    tokens: ['By default', 'all', 'cuff', 'lapel'],
    shownIn3D: false,
    visualModels: suit,
  },
  'jacket.threads.hole': {
    label: 'Buttonhole colour',
    keys: ['accents.jacket.button_holes_threads.button-holes'],
    tokens: THREAD_COLOURS,
    shownIn3D: false,
    visualModels: suit,
  },
  'jacket.threads.thread': {
    label: 'Button thread colour',
    keys: ['accents.jacket.button_holes_threads.button-threads'],
    tokens: THREAD_COLOURS,
    shownIn3D: false,
    visualModels: suit,
  },
  'jacket.lining': {
    label: 'Lining',
    keys: ['accents.jacket.lining.internal-lining'],
    tokens: ['default', 'personalizado', 'unlined', 'padded'],
    shownIn3D: false,
    visualModels: suit,
  },
  'jacket.liningFabric': {
    label: 'Lining fabric',
    keys: ['accents.jacket.lining.lining-fabrics'],
    tokens: [
      '98',
      '116',
      '81',
      '96',
      '173',
      '236',
      '174',
      '186',
      '110',
      '188',
      '168',
      '189',
      '217',
      '219',
      '79',
      '218',
      '215',
      '216',
      '184',
      '111',
      '169',
      '164',
      '167',
      '222',
      '224',
      '213',
      '220',
      '227',
      '194',
      '196',
      '231',
      '221',
      '230',
      '223',
      '198',
      '229',
      '191',
      '233',
      '282',
      '286',
      '281',
      '280',
      '279',
      '278',
      '276',
      '275',
      '274',
      '272',
      '271',
      '269',
      '283',
      '284',
      '285',
      '266',
      '287',
      '288',
      '289',
      '290',
      '291',
      '292',
      '293',
      '294',
      '251',
      '199',
      '197',
      '225',
      '226',
      '195',
      '193',
      '192',
      '234',
      '246',
      '249',
      '250',
      '268',
      '252',
      '253',
      '254',
      '255',
      '256',
      '257',
      '264',
      '265',
      '200',
      '267',
    ],
    shownIn3D: false,
    visualModels: suit,
  },
  'jacket.halfCanvas': {
    label: 'Canvas',
    keys: ['accents.jacket.half_canvas.canvas'],
    tokens: ['base', 'half_canvas'],
    shownIn3D: false,
    visualModels: suit,
  },
  'jacket.monogram.font': {
    label: 'Monogram font',
    keys: ['accents.jacket.initials.font'],
    tokens: ['bold_script', 'script', 'times_roman', 'block', 'calligraphy'],
    shownIn3D: false,
    visualModels: suit,
  },
  'jacket.monogram.thread': {
    label: 'Monogram thread',
    keys: ['accents.jacket.initials.thread-color'],
    tokens: THREAD_COLOURS,
    shownIn3D: false,
    visualModels: suit,
  },
  'jacket.elbowPatches': {
    label: 'Elbow patches',
    keys: ['accents.jacket.patches.elbow-patches'],
    tokens: ['Without', 'personalizado'],
    shownIn3D: false,
    visualModels: suit,
  },
  'jacket.elbowPatches.colour': {
    label: 'Elbow patch colour',
    keys: ['accents.jacket.patches.colors'],
    tokens: ['55', '56', '57', '58', '59'],
    shownIn3D: false,
    visualModels: suit,
  },
  'jacket.neckLining': {
    label: 'Neck lining',
    keys: ['accents.jacket.neck_lining.neck-lining'],
    tokens: ['By default', 'personalizado'],
    shownIn3D: false,
    visualModels: suit,
  },
  'jacket.neckLining.colour': {
    label: 'Neck lining colour',
    keys: ['accents.jacket.neck_lining.colors'],
    tokens: ['1', '2', '3', '4', '5', '6', '7'],
    shownIn3D: false,
    visualModels: suit,
  },
  'jacket.pocketSquare': {
    label: 'Pocket square',
    keys: ['accents.jacket.panuelos.pocket-squares'],
    tokens: OPTIONAL,
    shownIn3D: false,
    visualModels: suit,
  },
  'jacket.pocketSquare.product': {
    label: 'Pocket square choice',
    keys: ['accents.jacket.panuelos.products'],
    tokens: [
      '768',
      '811',
      '810',
      '779',
      '778',
      '777',
      '776',
      '775',
      '774',
      '773',
      '772',
      '771',
      '770',
      '769',
      '416',
      '767',
      '766',
      '765',
      '764',
      '763',
      '762',
      '418',
      '453',
      '423',
      '422',
      '421',
      '420',
    ],
    shownIn3D: false,
    visualModels: suit,
  },
  'trousers.fit': {
    label: 'Trouser fit',
    keys: ['style.pants.pants_fit.pants-fit'],
    tokens: ['normal', 'fit'],
    shownIn3D: true,
    visualModels: suit,
  },
  'trousers.length': {
    label: 'Trouser length',
    keys: ['style.pants.pants_length.pants-length'],
    tokens: ['long', 'bermuda'],
    shownIn3D: true,
    visualModels: suit,
  },
  'trousers.break': {
    label: 'Trouser break',
    keys: ['style.pants.pants_break.pants-break'],
    tokens: ['no', 'half', 'full'],
    shownIn3D: true,
    visualModels: suit,
  },
  'trousers.pleats': {
    label: 'Pleats',
    keys: ['style.pants.pants_peg.pants-peg'],
    tokens: ['0', '1', '2'],
    shownIn3D: false,
    visualModels: suit,
  },
  'trousers.fastening': {
    label: 'Trouser fastening',
    keys: ['style.pants.pants_belt.pants-belt'],
    tokens: ['0', '1', '0_hidden', '1_hidden'],
    shownIn3D: false,
    visualModels: suit,
  },
  'trousers.frontPocket': {
    label: 'Side pockets',
    keys: ['style.pants.pants_pockets.pants-front-pocket'],
    tokens: ['diagonal', 'rounded', 'rounded_chinos'],
    shownIn3D: false,
    visualModels: suit,
  },
  'trousers.backPocket': {
    label: 'Back pockets',
    keys: ['style.pants.pants_pockets.pants-back-pocket-combine'],
    tokens: ['0', 'A1', 'B1', 'C1', 'A2', 'B2', 'C2'],
    shownIn3D: false,
    visualModels: suit,
  },
  'trousers.cuffs': {
    label: 'Trouser cuffs',
    keys: ['style.pants.pants_cuff.pants-cuff'],
    tokens: ['0', '1'],
    shownIn3D: true,
    visualModels: suit,
  },
  'trousers.suspenderButtons': {
    label: 'Suspender buttons',
    keys: ['style.pants.suspender_buttons.suspender-buttons'],
    tokens: ['0', '1'],
    shownIn3D: false,
    visualModels: suit,
  },
  'trousers.waist': {
    label: 'Waist adjustment',
    keys: ['style.pants.active_waist.active-waist'],
    tokens: ['0', '2', '1'],
    shownIn3D: false,
    visualModels: suit,
  },
  'trousers.belt': {
    label: 'Belt',
    keys: ['accents.pants.belt.belt'],
    tokens: OPTIONAL,
    shownIn3D: false,
    visualModels: suit,
  },
  'trousers.braces': {
    label: 'Braces',
    keys: ['accents.jacket.suspenders.braces'],
    tokens: OPTIONAL,
    shownIn3D: false,
    visualModels: suit,
  },
  'vest.style': {
    label: 'Vest style',
    keys: ['style.vest.waistcoat_style_combined.waistcoat-style-combined'],
    tokens: ['simple_4', 'simple_5', 'crossed_6'],
    shownIn3D: true,
    visualModels: suit,
  },
  'vest.lapel': {
    label: 'Vest lapels',
    keys: ['style.vest.waistcoat_lapel.waistcoat-lapel'],
    tokens: ['no', 'notched', 'peak', 'rounded'],
    shownIn3D: false,
    visualModels: suit,
  },
  'vest.bottom': {
    label: 'Vest edge',
    keys: ['style.vest.waistcoat_bottom.waistcoat-bottom'],
    tokens: ['straight', 'cut'],
    shownIn3D: true,
    visualModels: suit,
  },
  'vest.chestPocket': {
    label: 'Vest breast pocket',
    keys: ['style.vest.waistcoat_chest_pocket.waistcoat-chest-pocket'],
    tokens: ['1', '0'],
    shownIn3D: false,
    visualModels: suit,
  },
  'vest.pockets': {
    label: 'Vest pockets',
    keys: ['style.vest.waistcoat_pockets.waistcoat-pockets'],
    tokens: ['0', '2', '2a', '2b'],
    shownIn3D: false,
    visualModels: suit,
  },
  'shirt.collar': {
    label: 'Shirt collar',
    keys: ['style.shirt.shirt_collar.shirt-collar'],
    tokens: ['spread', 'point'],
    shownIn3D: true,
    visualModels: ['shirt'],
  },
  'shirt.cuffs': {
    label: 'Shirt cuffs',
    keys: ['style.shirt.shirt_cuffs.shirt-cuffs'],
    tokens: ['button', 'french'],
    shownIn3D: true,
    visualModels: ['shirt'],
  },
  'tie.on': {
    label: 'Necktie',
    keys: ['accents.jacket.tie.necktie'],
    tokens: OPTIONAL,
    shownIn3D: false,
    visualModels: suit,
  },
  'tie.product': {
    label: 'Necktie choice',
    keys: ['accents.jacket.tie.products'],
    tokens: [
      '751',
      '761',
      '760',
      '759',
      '758',
      '757',
      '756',
      '755',
      '754',
      '753',
      '752',
      '741',
      '750',
      '749',
      '748',
      '747',
      '746',
      '745',
      '744',
      '743',
      '742',
    ],
    shownIn3D: false,
    visualModels: suit,
  },
  'bowtie.on': {
    label: 'Bow tie',
    keys: ['accents.jacket.bowtie.bowtie'],
    tokens: ['No bow tie', 'personalizado'],
    shownIn3D: false,
    visualModels: suit,
  },
  'bowtie.product': {
    label: 'Bow tie choice',
    keys: ['accents.jacket.bowtie.products'],
    tokens: [
      '386',
      '820',
      '821',
      '822',
      '823',
      '824',
      '825',
      '383',
      '384',
      '385',
      '387',
      '388',
      '389',
    ],
    shownIn3D: false,
    visualModels: suit,
  },
  'shoes.on': {
    label: 'Shoes',
    keys: ['accents.jacket.shoes.shoes'],
    tokens: ['By default', 'personalizado'],
    shownIn3D: true,
    visualModels: suit,
  },
  'shoes.product': {
    label: 'Shoe choice',
    keys: ['accents.jacket.shoes.products'],
    tokens: ['145391', '275802', '300077', '398342', '876664', '999484', '1050838'],
    shownIn3D: true,
    visualModels: suit,
  },
  'socks.on': {
    label: 'Socks',
    keys: ['accents.pants.socks.socks'],
    tokens: OPTIONAL,
    shownIn3D: false,
    visualModels: suit,
  },
  'socks.product': {
    label: 'Sock choice',
    keys: ['accents.pants.socks.products'],
    tokens: [
      '834',
      '842',
      '841',
      '840',
      '839',
      '838',
      '837',
      '836',
      '835',
      '782',
      '791',
      '789',
      '788',
      '787',
      '786',
      '785',
      '784',
    ],
    shownIn3D: false,
    visualModels: suit,
  },
} as const satisfies Record<string, VisualSlot>;

export type SlotId = keyof typeof VISUAL_SLOTS;
export const SLOT_IDS = Object.keys(VISUAL_SLOTS) as SlotId[];

/**
 * Selection keys the renderers read that are not slots: the vest is drawn when
 * the `vest` component is included (CATALOG-ADMIN §10), not from a choice.
 */
export const COMPONENT_DRIVEN_KEYS = { 'style.vest.waistcoat.waistcoat': 'vest' } as const;

export const REGION_IDS = Object.keys(REGIONS) as RegionId[];

export function isSlotId(value: unknown): value is SlotId {
  return typeof value === 'string' && Object.hasOwn(VISUAL_SLOTS, value);
}
export function isRegionId(value: unknown): value is RegionId {
  return typeof value === 'string' && Object.hasOwn(REGIONS, value);
}

const slotByKey = new Map<string, SlotId>(
  SLOT_IDS.flatMap((slot) => VISUAL_SLOTS[slot].keys.map((key) => [key, slot] as const)),
);
/** The slot an attribute code (selection key) drives, if the renderers draw it. */
export function slotForKey(key: string): SlotId | undefined {
  return slotByKey.get(key);
}
/** Whether a choice's token is drawable for a slot (`visual_token_unknown` otherwise). */
export function isTokenOf(slot: SlotId, token: string) {
  return (VISUAL_SLOTS[slot].tokens as readonly string[]).includes(token);
}
